name: Test and Deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install
          
      - name: Build CSS
        run: |
          npm run build:css
          
      - name: Run security tests
        run: |
          python tests/test_admin_security.py
          python tests/test_admin_py_security.py
          python tests/test_test_integrity.py
          
      - name: Run regression tests
        run: |
          python tests/test_admin_routes_regression.py
          python tests/test_admin_portal_access.py
          python tests/test_admin_portal_production_fixes.py
          
      - name: Validate environment configuration
        run: |
          python env_validator.py
        env:
          PYTEST_CURRENT_TEST: 1
          DATABASE_URL: postgresql://test:test@localhost:5432/testdb
          SMTP_SERVER: smtp.gmail.com
          SMTP_PORT: 587
          SMTP_USERNAME: test@example.com
          SMTP_PASSWORD: testpassword

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Trigger Render Deploy
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
        if: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          
      - name: Health check
        run: |
          echo "Waiting for deployment to complete..."
          sleep 60
          curl -f https://logicandstories.onrender.com/health || echo "Health check failed, but deployment may still be in progress"